<?php

/**
 * @file
 */

/**
 * @file
 * Contains ehealth.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ehealth_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ehealth module.
    case 'help.page.ehealth':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('E-health registration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ehealth_theme($existing, $type, $theme, $path) {
  return [
    'pixel_reg' => [
      'variables' => ['content' => NULL],
    ],
  ];
}
