zen_rebuild_registry: 0
_core:
  default_config_hash: P5V06zRKs-pLgT92nugyuXkhg3tCsItyIcJqjLrjmaM
features:
  node_user_picture: 0
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 1
logo:
  use_default: 0
  path: themes/behave/images/BehaveNet-logo-with-text.jpg
favicon:
  use_default: 0
  path: themes/behave/images/favicon.ico
  mimetype: image/vnd.microsoft.icon
