favicon:
  mimetype: image/vnd.microsoft.icon
  path: themes/behave/images/favicon.ico
  url: ''
  use_default: false
features:
  comment_user_picture: false
  comment_user_verification: false
  favicon: true
  node_user_picture: false
logo:
  path: themes/behave/images/BehaveNet-logo-with-text.jpg
  url: ''
  use_default: false
_core:
  default_config_hash: 9rAU4Pku7eMBQxauQqAgjzlcicFZ2As6zEa6zvTlCB8
